import { Inter , Montserrat,Poppins} from 'next/font/google'
import '../globals.css'
import Navbar from '../component/Navbar'

const inter = Inter({ subsets: ['latin'] })
const mont=Montserrat({subsets:['latin'],weight:["400","600","700"],variable:"--body-font"})
const poppins=Poppins({subsets:['latin'],weight:["400","600","700"],variable:"--poppins"})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function ProductLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${mont.className} ${poppins.className} relative`}>
        <Navbar/>
          {children}
      </body>
    </html>
  )
}
